type Suggestion {
  id: ID!
  title: String
  description: String
  tags: [String]
  upvotes: Int
  comments: Int
}

type Comment {
  user: User
  comment: String
  replies: [Reply]
}

type Tags {
  names: [String]
}

type Query {
  suggestionList: [Suggestion]
  tags: [Tags]
}
